### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/glassfish-jsftemplating#53]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by arjantijms** [comment]
Project CI environment has been requested:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=538690

**Comment by senivam** [comment]
master build job:
https://jenkins.eclipse.org/glassfish/view/jsftemplating/job/jsftemplating-master-build/
EE4J_8 build job:
https://jenkins.eclipse.org/glassfish/view/jsftemplating/job/jsftemplating-EE4J-build/

however EE4J_8 branch contains failing tests which makes build yellow...
